### ISSUE TITLE
Not working !!!! Please Update !!!!

### ISSUE THREAD

**Issue by ba1ma0** [ax/burp-logs#3]
I  use the  extension to import burp log file ! But there is nothing happen! 
![截屏2022-08-11 15 42 46](https://user-images.githubusercontent.com/32502627/184086879-80d2d180-fb33-4c78-b6a2-c2bf87c63761.png)
![截屏2022-08-11 15 43 48](https://user-images.githubusercontent.com/32502627/184086905-d99b6b55-2117-4bef-949f-f1e310fe9741.png)

**Comment by ax** [comment]
Hi ba1ma0,
have you checked your log file content?
Also, which version of Burp are you using?

**Comment by ba1ma0** [comment]
Before i installed the extension from BApp Store and i tried many times But it did not work
then i compiled the https://github.com/portswigger/log-viewer ! Installed from a jar file and import the same log file!Now  it works  !
Thanks for your kind answer!😃😃
<img width="528" alt="截屏2022-08-11 16 21 46" src="https://user-images.githubusercontent.com/32502627/184092806-0d50d5f9-001d-4095-bccb-e1c093bd35d9.png">

**Comment by ax** [comment]
:) Closing.
